### ISSUE TITLE
No difference between killKeepAliveThreadExecutor and killCancelableThreadExecutor

### ISSUE THREAD

**Issue by Spierki** [MathiasSeguy-Android2EE/ForecastYahooRest#3]
I don't understand how the keep alive threads can finish there jobs as there is no difference between the functions killKeepAliveThreadExecutor and killCancelableThreadExecutor in the ServiceManager.

Thanks in advance !

**Comment by MathiasSeguy-Android2EE** [comment]
Hey,
The difference between those two methods is subtle and have 3 characters :"NOW"
If you look again at the code, you'll se that 
- KillCancelable  use the method shutDownNow on the executor
- KillKeepAlive will use the method shutDown on the executor associated.


Those two methods are deeply different:
ShutDown just tell to the executor to stop accepting new submission 
ShutDownNow tell also to the executor to stop accepting new submission but also fire the interrupt event to each Thread it manages. So the Thread should stop and catch the interruption exception.    
This is the main difference, ShutDown just tells ok, keep doing the job but don't accept new one and ShutDownNo tells, stop the Thread that are still active and don't accept new job.

You're welcome, thanks for the question.
